# Generated by Django 3.2.4 on 2021-06-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('nombre', models.CharField(max_length=100, verbose_name='Name')),
                ('telefono', models.CharField(max_length=100, verbose_name='Phone')),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Email')),
                ('direccion', models.CharField(max_length=100, verbose_name='Address')),
                ('mensaje', models.CharField(max_length=500, verbose_name='Message')),
            ],
        ),
    ]
